# Generated by Django 3.2.8 on 2021-10-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='fechaMatricula',
            field=models.DateTimeField(auto_now_add=True, default='America/Bogota'),
            preserve_default=False,
        ),
    ]
